sudo: required
os: osx

branches:
  only:
    - master

before_install:
  - brew update

install:
  - brew install ansible

script:
  - git clone https://github.com/benmezger/dotfiles.git ~/dotfiles
  - (cd ~/dotfiles; git checkout osx)
  - ansible-playbook -i inventory osx.yml

