---
- hosts: localhost
  pre_tasks:
    - pause:
        prompt: "App Store email (mas)"
      when: lookup('env', 'TRAVIS') == '0'
      register: "mas_email"
    - pause:
        prompt: "App store password (mas)"
      when: lookup('env', 'TRAVIS') == '0'
      register: "mas_password"
  roles:
    - role: common
    - role: osx
