---
- name: Clone Aura
  git:
    repo: https://aur.archlinux.org/aura-bin.git
    dest: /tmp/aura-bin
    force: yes

- name: Build and install Aura
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/aura-bin

- import_tasks: pacman.yml
- import_tasks: ../../linux/tasks/services.yml
- import_tasks: ../../linux/tasks/python.yml

- name: Restore files using GNU Stow
  command: stow {{ item }}
  args:
    chdir: ~/dotfiles
  with_items:
    - bin
    - config
    - git
    - gnupg
    - ipython
    - misc
    - tmux
    - vim
    - zsh
    - X

- name: Ensure vim directories exist
  file:
    path: ~/.vim/autoload
    state: directory

- name: Install Vim-Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
