---
- import_tasks: emerge.yml
- import_tasks: ../../linux/tasks/services.yml
- import_tasks: ../../linux/tasks/python.yml

- name: Restore files using GNU Stow
  command: stow {{ item }}
  args:
    chdir: ~/dotfiles
  with_items:
    - bin
    - config
    - git
    - gnupg
    - ipython
    - misc
    - tmux
    - vim
    - zsh
    - X
    - virtualenvs
