---
- name: Install zplug
  git:
    repo: https://github.com/zplug/zplug
    dest: ~/.zplug

- name: Clone dotfiles
  git:
    repo: https://github.com/benmezger/dotfiles.git
    dest: ~/dotfiles

- name: Clone TPM (for Tmux)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Ensure vim directories exist
  file:
    path: ~/.vim/autoload
    state: directory

- name: Install Vim-Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
