---
- name: Tap fonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install Homebrew packages
  homebrew:
    state: latest
    name:
      - vim
      - fasd
      - ack
      - gnupg2
      - tmux
      - tor
      - reattach-to-user-namespace
      - stow
      - pinentry-mac
      - git
      - the_silver_searcher
      - diff-so-fancy
      - cmake
      - mas
      - fish
      - xz
      - readline
      - pyenv

- name: Install apps using Homebrew Cask
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - google-chrome
    - transmission
    - iterm2
    - vlc
    - skype
    - spotify
    - docker
    - 1password
    - hopper-disassembler
    - java
    - ckb-next

- name: Install fonts using Homebrew Cask
  homebrew_cask:
    name: font-inconsolata-dz
    state: present

- name: Cleanup Homebrew packages
  command: brew cleanup -s

