---
- import_tasks: brew.yml
- import_tasks: python.yml
- import_tasks: mas.yml
  when: lookup('env', 'TRAVIS') == '0'

- name: Restore files using GNU Stow
  command: stow {{ item }}
  args:
    chdir: ~/dotfiles
  with_items:
    - bin
    - git
    - gnupg
    - ipython
    - misc
    - tmux
    - vim
    - zsh


- name: Ensure vim directories exist
  file:
    path: ~/.vim/autoload
    state: directory

- name: Install Vim-Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

