---
- name: Install Python packages using pip
  pip:
    executable: pip2
    name:
      - virtualenvwrapper
      - ipython
      - grasp
      - neovim
      - notebook
      - jupyter
      - flake8
      - pep8
